apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-test
  region: us-east-1
  version: "1.23"

nodeGroups:
  - name: workers
    instanceType: m5.xlarge
    desiredCapacity: 3
    ssh:
      allow: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eks-test: "owned"

cloudWatch:
  clusterLogging:
    enableTypes:
      - "all"
    logRetentionInDays: 60